### PR TITLE
Added Russian language

### PR DESCRIPTION
**Pull request by cjmaxik**

### CODE REVIEW

**Comment by shardick** [comment]
Thank you!

Can you add also "russian" as property with translated value please?

**Comment by cjmaxik** [comment]
Added.
But, tbh, I didn't see the point of translating languages name. Also, it would be great to have translations in separated files.

**Comment by shardick** [comment]
I was thinking on that (translating language names) and i'm realizing that could be better not translate them, as you pointed out.

**Comment by shardick** [comment]
Hi @cjmaxik , new labels to translate added to english resources. Could you integrate your translations please?

**Comment by shardick** [comment]
Hi @cjmaxik  , new labels to translate added to english resources. Could you integrate your translations please?

**Pull request merged**
